name: Format

on:
  push:
    branches:
      - master
    paths:
      - README.md

jobs:
  format_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Format README.md
        run: npx -y prettier --write README.md

      - name: Commit format of README.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: format README.md"
