name: test

on:
  push:
    branches:
      - master
    paths:
      - plugins/*
      - README.md

jobs:
  all_plugins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check new plugin is registered correctly
        run: bash scripts/test_plugin.bash --all
