name: Lint

on:
  pull_request:
    paths:
      - "plugins/*"

jobs:
  check_plugin_registration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Check formatting
        run: npx prettier --check README.md

      - name: Check new plugin is registered correctly
        run: bash test_plugin.sh --diff origin/master ${{ github.sha }}
